Feat/95 food preferences
kakao-tech-campus-2nd-step3/Team16_FE pull request #102
Opened 2024-11-07 06:19 UTC by HyeonChae1104

## 주요 변경사항 ✔️
### 선호/비선호 음식 조회, 추가 및 삭제 기능 구현
현재 선호/비선호 음식 조회 및 관리 기능을 구현하였습니다. 개발자 도구로 확인해본 결과, 음식 조회, 추가, 삭제 요청이 정상적으로 서버에 전달되고 있습니다.

### 검색 및 추가 기능
사용자가 메뉴를 검색하면, 입력한 키워드와 일치하는 음식이 실시간으로 하단에 리스트업됩니다. 검색 결과에서 추가하고 싶은 음식을 선택하면 POST 요청이 전송되며, 선택된 음식이 선호/비선호 목록에 추가됩니다.

### 삭제 기능
사용자가 추가한 음식 항목을 다시 클릭하면, 해당 음식이 DELETE 요청을 통해 목록에서 삭제됩니다.

## 리뷰어에게... 🙏
추가로 구현할 부분
현재 마이페이지에 들어갔을 때 보여지는 기본 UI 틀을 추가하지 못한 상태입니다. 
추가해야 할 UI는 다음과 같습니다:
- 마이페이지에 접속 시 보이는 선호/비선호 음식 UI
- 그곳에서 추가(카테고리 선택 및 검색), 삭제할 수 있는 인터페이스로 이동하는 로직

UI 틀 부분은 프로필 조회(MyPage와 MyPageContainer)에 대한 리뷰를 반영하여 수정 후, 바로 진행할 계획입니다.

## 관련 이슈

closes #95

2024-11-07 12:05 UTC, Da-Yeon-Kim reviewed
혹시 이전에 작업하시던 `feat/64-profile-retrieval` 브랜치에서 분화하셨나요?
그 브랜치의 내용도 함께 적용되어서 실행 시 오류가 발생하네요😅

2024-11-08 01:03 UTC, geongyu09 requested changes
일단 올바르게 돌아가지 않는 상태이므로 수정 요청합니다.
현재 prettier적용이 안되어 있는 곳이 존재합니다
그리고 저번에도 리뷰에 남겼었지만, 컨밴션을 어기려면 그에 대한 합당한 이유를 팀원에게 제시하고 설득시켜야 합니다. 
그에대한 설명이 없는게 조금 아쉽네요

2024-11-08 01:03 UTC, geongyu09 commented on src/api/hooks/useFoodPreference.ts
> +  const fetchFoodsByCategory = async (category: string) => {
prettier가 적용이 안되어있어요..

2024-11-08 01:03 UTC, geongyu09 commented on src/api/hooks/useFoodPreference.ts
> +    const response = await axios.get<{ data: Food[] }>(`${baseURL}/api/foods`, {
음... 여기서 axios를 부르면 안될 것 같네요

2024-11-08 01:03 UTC, geongyu09 commented on src/api/hooks/useUserPreferences.ts
> +  return {
혹시 음식 추가, 삭제코드를 한번에 작성한 이유가 있나요?? 좋
책임적으로 좋아보이긴 하네요

2024-11-08 01:03 UTC, geongyu09 commented on src/api/hooks/useUserPreferences.ts
> +    queryFn: async () => {
함수를 분리하지 않고 queryFn에 한번에 작성한 이유가 있나요?

2024-11-08 01:03 UTC, geongyu09 commented on src/api/mock/food.mock.ts
> +  rest.get(`${baseURL}/api/foods`, (req, res, ctx) => {
url 로직이 반복되네요. 기존에 작성되얻오던 로직은 이를 방지하는데, 혹시 변경한 이유가 있나요?

2024-11-08 01:03 UTC, geongyu09 commented on src/components/features/Food/FoodSelector.tsx
> +  const handleFoodSelect = (food: Food) => {
어떤 핸들러는 따로 훅으로 뺴고, 어떤 핸들러는 빼지 않았네요. 혹시 그 기준이 뭔가요?

2024-11-08 01:03 UTC, geongyu09 commented on src/components/features/MyPageContainer/index.tsx
> +import React from 'react';
해당 문장은 제거해도 될 것 같습니다

2024-11-08 01:03 UTC, geongyu09 commented on src/index.tsx
> +    await worker.start({ onUnhandledRequest: 'bypass',});
혹시 bypass 설정한 이유가 있나요? 
추가적으로 prettier가 설정이 안되어있네요

2024-11-08 01:03 UTC, geongyu09 commented on src/pages/MyPage/index.tsx
> +      <FoodSelector initialFoods={preferredFoods} type="preferred" onAddFood={addPreferredFood} onDeleteFood={deletePreferredFood} />
foodSection에 type을 안받고 있는 것 같습니다
추가적으로 type 에 맞추어서 분기처리하는 것은 올바른 추상화가 아니라고 생각합니다만, 
그리 중요한 문제는 아니니 넘어가도 좋아보이네요

2024-11-08 10:57 UTC, HyeonChae1104 commented
feat/64-profile-retrieval 브랜치에서 분화한 것은 아닌데.. 
feat/64-profile-retrieval에서 수정을 위해 머지 하지 않았던 상황에서 현재 브랜치에서 사용했던 파일이 똑같아서 문제가 발생했습니다.!ㅜ

이 PR은 닫고, 리뷰해주신 내용 전부 꼼꼼하게 반영하여 새로운 PR을 날리도록 하겠습니다! 최대한 빠르게 하겠습니다!

2024-11-08 11:00 UTC, closed without merging