[Chore] style 초기화
kakao-tech-campus-2nd-step3/Team16_FE pull request #6
Opened 2024-09-20 08:09 UTC by HyeonChae1104

##주요 변경사항
- reset-css를 설정하여 기존의 스타일을 초기화하였습니다. 
- breakpoints를 정의하고 적용하였습니다. (styles/variants/index.ts)

##리뷰어에게...
부족한 부분이 있다면 피드백 부탁드립니다! 

##관련 이슈
closes #4

2024-09-20 08:40 UTC, geongyu09 requested changes
올바르게 reset-css가 적용되지 않은 것 같습니다..! 
reset.css 파일은 올바르게 만들었지만, 해당 파일이 적용이 안되고 있습니다

index.css 부분과 app.css 부분을 올바르게 수정하고, 실제 ts/tsx 파일에 적용되어야 할 것 같습니다!

2024-09-20 11:22 UTC, geongyu09 reviewed
몇가지 더 남겨보았습니다! 
저희가 왜 이런 폴더구조를 가지고, 왜 index.ts 파일이 존재하는지에 대해서 조금 더 생각해봐도 좋을 것 같습니다! 

변경이 어려우시면 언제든 연락해주세요! 
그리고 pr에 변경사항이 생긴다면 오른쪽 위에 리뷰어 설정 부분에 화살표로 원 그려진 부분 클릭하면 re-request 할 수 있어요. 변경 사항 생기면 꼭 눌러주세요! 
(안누르면 메일 알림도 안오고, 저도 커맨드밖에 달지 못해요!)

2024-09-20 11:22 UTC, geongyu09 commented on src/App.css
> +@import "./styles/reset.css";
단순히 저희가 reset.css 파일을 import 하면 지금것 만들었던 계층 구조가 깨지게 됩니다.
현재 저희는 만들어질 수 있는 css 파일을 전부 styles에 넣어두고, 이를 /styles/index.ts에 import 하고 있습니다. 
즉 모든 css에 대한 정보는 index.ts를 거쳐서 나가도록 하고 있어요. 
그리고 index.ts만 실제 저희 프로젝트에 적용하고 있죠.
덕분에 관리가 정말 편하고 저희 프로젝트에서는 css에 대해서 큰 관심을 가지지 않고 react 로직에만 집중할 수 있게 해줍니다. 

해당 로직은 `css-> index.ts ->프로젝트`  단계대로 작성된 것이 아니라 `reset.css -> App.css -> 프로젝트` 로 가게 되는 로직인 것 같습니다. 
수정이 필요해보입니다. 

아래 절차대로 하면 됩니다. 

1. App.css, index.css 제거
2. /src/index.tsx에 `import '@/styles';` import 문 추가
  (헌재 craco 이슈가 있으므로 `import './styles/index';` 로 대체해도 좋습니다.)

2024-09-20 11:22 UTC, geongyu09 commented on src/styles/reset.css
> +html {
추가적으로 확인해보니 해당 reset.css 로직에도 font-size 초기화 로직이 빠지는 등 문제가 있는 것 같습니다. 
아래의 로직으로 변경 부탁드립니다! 

<details>
<summary>
reset.css 로직
</summary>
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
</details>

2024-09-20 12:11 UTC, Da-Yeon-Kim commented on src/App.css
> +@import "./styles/reset.css";
오, 제가 하고 싶은 말을 건규 씨가 이미 엄청 친절하게 작성해주셨네요! ㅎㅎ
건규 씨가 말씀해주신 부분들은 2단계 프로젝트와 유사해서
그때 코드를 좀 참고하시면, 폴더 구조나 로직에 대한 이해가 더 수월하실 거예요~

2024-09-20 14:05 UTC, HyeonChae1104 commented on src/styles/reset.css
> +html {
해당 로직으로 변경하였습니다!

2024-09-20 14:06 UTC, HyeonChae1104 commented on src/App.css
> +@import "./styles/reset.css";
꼼꼼하게 남겨주셔서 감사합니다! 잘 읽어보고 알려주신대로 수정해보았습니다.!

2024-09-20 14:36 UTC, geongyu09 requested changes
한번 더 수정해야할 것 같아요..

2024-09-20 14:36 UTC, geongyu09 commented on src/index.tsx
> +import '@styles/index'
`@/styles/index` 로 수정해야합니다

2024-09-20 14:37 UTC, HyeonChae1104 commented on src/index.tsx
> +import '@styles/index'
헉.. 넵..!

2024-09-20 14:39 UTC, Da-Yeon-Kim commented on src/index.tsx
> +import '@styles/index'
그리고 index는 자동으로 인식되니까 굳이 안 적으시고 `@/styles`만 적으셔도 되어요:D
명시하셔도 큰 상관은 없지만, 보통 적지 않으니 통일성을 주는 게 좋을 것 같긴 해요~

2024-09-21 07:45 UTC, geongyu09 approved these changes
reset-css가 올바르게 적용이 되었네요! 
추가적으로 수정할 부분이 있긴 있어보이지만, 중요한 사항은 아니므로 approve 하였습니다!

craco, react-router-dom은 이미 merge가 되었던 다른 pr에서 작업한 내용이라서 꼭 필요한 작업은 아니었다고 생각합니다! 
이러한 것들은 오히려 컨플릭이나 기존에 해결되었던 문제들을 다시 일으킬 수도 있고 버전이 다를 수도 있게 되므로 주의가 필요합니다. 
해결하려는 이슈와 다른 성격을 가지고 있기도 하므로 이러한 것들을 꼭 해당 pr 내용에 담아야 했다면, 그 이유를 다른 피어분들에게 충분히 설명해줄 필요도 있어보입니다! 

고생많으셨습니다! 그대로 머지해도 괜찮아 보이지만 시간적 여유가 된다면 src/index.tsx 부분 수정해주세요~~!

2024-09-21 07:45 UTC, geongyu09 commented on src/index.tsx
> +export {};
해당 로직은 불필요해보입니다! 제거해도 좋아보입니다

2024-09-21 07:45 UTC, geongyu09 commented on src/index.tsx
> +import "@/styles"
👍👍👍👍

2024-09-21 07:47 UTC, geongyu09 commented
컨플릭 해결하게 되면 커밋이 하나 쌓이게 됩니다! 
해당 커밋도 가능하다면 컨밴션을 지켜주세요!

2024-09-21 09:18 UTC, Da-Yeon-Kim approved these changes

2024-09-21 11:45 UTC, merged