[FEAT] KakaoLogin 구현_재PR
kakao-tech-campus-2nd-step3/Team16_FE pull request #75
Opened 2024-10-28 06:43 UTC by HyeonChae1104

## 주요 변경사항 ✔️

1. `FailurePage`: 로그인 실패 시 리다이렉트 되는 페이지
2. `SuccessPage` : 로그인 성공 시 리다이렉트 되는 페이지
3. `useSuccessLogin.ts` : 로그인 성공 시 백엔드에서 전달 받은 쿠키에서 accessToken을 확인하여 localStorage에 저장한 후 보안을 위해 삭제합니다.

4. `useHandleKakaoLogin` : 
- 로그인 실패 시 login page로 이동
- GET요청을 통해 백엔드로 리다이렉트

5. `useFetchWithToken`
연우님이 토큰 재발급에 대한 부분을 이렇게 처리해보면 어떨지 제안을 주셔서 회의 후 구현해보았습니다!
- 401 응답 시 토큰 재발급을 위한 useFetchWithToken 추가
- accessToken 만료 시 토큰 재발급을 처리하는 useFetchWithToken 훅 생성
- Axios 인터셉터를 통해 토큰 재발급 후 요청을 자동 재시도하도록 구현
- 토큰 재발급 실패 시 로그인 페이지로 리다이렉트

## 리뷰어에게... 🙏
지난번에 리뷰해주신 부분은 반영을 해보았습니다.
코드에서 잘못된 부분이 있는지 확인 부탁드립니다.! 
커밋은 가장 최근것부터 7개 봐주시면 좋을 것 같습니다!(rebase 하는 중에 충돌이 너무 많이 생겨 전부 다 하지는 못했습니당..)

## 관련 이슈
closes #40

2024-10-28 09:45 UTC, Da-Yeon-Kim commented
저녁에 집 가서 살펴보겠습니다! 저도 로그인 로직을 잘 몰라서 열심히 봐봐야 할 것 같아요😅
슬쩍 봐보니 merge conflict 정리가 덜 된 것 같은데, 일단 리뷰 먼저 받으려고 미완인 채로 올려두신 건가요??

2024-10-28 10:16 UTC, geongyu09 requested changes
말씀 하신대로 전체적으로 충돌이 해결되지 않은 것 같아요.
충돌을 전부 다 해결하고, 돌아가는 코드가 되어야 올바르게 리뷰를 할 수 있을 것 같아요..

깃 관련된 내용을 제외하고 로직 부분으로만 리뷰를 남겨보았습니다. 
충돌 해결하고 몇가지 수정된 이후에 다시 재요청 해주세요!

2024-10-28 10:16 UTC, geongyu09 commented on src/api/hooks/useFetchWithToken.ts
> +  const navigate = useNavigate();
유저레벨의 훅을 api 레벨에서 사용하는건 올바르지 않아보입니다. 
useNavigate는 컴포넌트에서 사용하는걸로 수정해야할 것 같아요

실제 api 에서 요청하는 로직만 있는게 아니라 리다이렉트까지 책임을 가지게 되면, 나중에 이해할 수 없는 동작을 하는데 원인을 못찾는 경우가 발생합니다. 
흔히 이야기 하는 사이드이팩트가 이런 경우입니다

추후 혼란 방지를 위해서 책임은 하나만 가지도록 하는게 좋아보입니다

2024-10-28 10:16 UTC, geongyu09 commented on src/api/hooks/useFetchWithToken.ts
> +  const navigate = useNavigate();
추가적으로 인터셉터가 훅 내부에 있는건 이전까지 저희가 작성해왔던 계층구조와 맞지 않는 것 같습니다. 
이전의 코드에서는 인터셉터는 instance에 존재합니다. 
해당 로직도 instance에 있어야 할 것 같습니다. 

그리고 해당 파일에는 동일한 인스턴스의 인터셉터가 존재하므로 동작 또한 겹치게 될 것 같습니다. 
해당 인스턴스는 현재 어플리케이션 전체적으로 사용중이므로 꼭 문제가 없도록 만들어주세요

2024-10-28 10:16 UTC, geongyu09 commented on src/api/hooks/useHandleKakaoLogin.ts
> +      window.location.href ='url';  //추후 수정
여기는 왜 navigate를 안쓰고 window를 사용하셨나요? 
혹시 그 이유가 있을까요?

2024-10-28 10:16 UTC, geongyu09 commented on src/api/hooks/useHandleKakaoLogin.ts
> +      window.location.href ='url';  //추후 수정
해당 로직은 api 의 성격과 맞지 않아보이네요.
이전에 저희가 짜왔던 로직에는 url을 가져오는 로직과 해당 url로 fetch를 날리는 axios문, 그리고 이를 스케줄링하는 query문이 있습니다.

2024-10-28 10:16 UTC, geongyu09 commented on src/api/hooks/useSuccessLogin.ts
해당 파일도 api 로직과는 성격이 맞지 않아보입니다. 
다른 곳으로 옮길 필요가 있어보이네요

2024-10-28 10:16 UTC, geongyu09 commented on src/api/hooks/useSuccessLogin.ts
프론트단에서 쿠키를 만지는 것은 문제가 있습니다. 
쿠키를 프론트에서 만질 수 있다는 건, 제 3자가 이를 이용할 수 있다는 말과도 동일합니다
쿠키의 모든 책임은 서버에 두는 것이 맞습니다. 

만약 단순히 토큰을 주고 받는 것이라면 이를 로컬스토리지에 저장하는것이 조금 더 바람직해보이네요.

백엔드에서 쿠키로 넣어주는 상황이라면 프론트에서 만질 수 없도록 설정해주라고 해야합니다

2024-10-28 10:16 UTC, geongyu09 commented on src/api/hooks/useHandleKakaoLogin.ts
> +export const useHandleKakaoLogin = () => {
혹시 핸들러를 다른 파일로 뺀 이유가 있으신가요?
저의 예상으로는, 다른 곳에서 해당 로직을 재사용 하는 경우가 있나요?
재사용해야한다면 도메인을 제외하고 훅으로 만들어야 하지 않을까 싶어요

2024-10-28 10:16 UTC, geongyu09 commented on src/pages/Onboarding/index.tsx
> +  handleKakaoLogin: () => void; // props로 로그인 로직을 받음
혹시 페이지 컴포넌트에서 props를 받아야 하는 이유가 있나요?
아마 최상위 컴포넌트가 page컴포넌트일텐데, 그 위에서 라우팅을 만들어주는 로직에서 굳이 넣어줘야할 이유가 있을까 싶어요. 
그것도 버튼 컴포넌트에서만 사용되는 이밴트 핸들러인데, 그 위에 있는 페이지 컴포넌트도 이 로직을 알게 되고, 의미 없이 내려주기만 하고 있어요. 
@HyeonChae1104 님의 의도가 궁금합니다

2024-10-28 10:16 UTC, geongyu09 commented on e --abort
해당 파일이 커밋에 들어간 이유가 있나요....?
해당 파일을 생성한 이유는 무엇인가요?

2024-10-30 15:06 UTC, Da-Yeon-Kim commented
git 해결 되셨을까요?!
혹시 git이 제대로 꼬여서 해결이 어렵다면, 그냥 코드는 따로 복붙 해두고
아예 Weekly9에서 새로 브랜치 만들어서 다시 PR 날리는 것도 나쁘지 않아 보여요.....
git은 git으로 해결하는 게 좋긴 하지만, 지금은 시간 상😥

2024-10-30 16:18 UTC, HyeonChae1104 commented on e --abort
삭제하였습니다!

2024-10-30 16:19 UTC, HyeonChae1104 commented on src/api/hooks/useSuccessLogin.ts
백과 협의 후 방식을 바꾸었습니다! 감사합니다

2024-10-30 16:26 UTC, HyeonChae1104 commented on src/api/hooks/useHandleKakaoLogin.ts
> +      window.location.href ='url';  //추후 수정
window를 사용해서 get요청을한 이유는 백에서 get 요청에 대한 응답이 아닌 ,카카오로그인으로 redirect를 시키는 로직을 사용하셨습니다. 따라서 그 자리에서 무한히 기다리는 것이 아닌 응답을 기다리지 않는 `window.location.href`를 사용하였습니다.

2024-10-30 16:43 UTC, HyeonChae1104 commented on src/api/hooks/useHandleKakaoLogin.ts
> +      window.location.href ='url';  //추후 수정
해당 로직은 `Login/index.tsx` 파일로 옮겼습니다!

2024-10-30 16:54 UTC, HyeonChae1104 commented on src/api/hooks/useFetchWithToken.ts
> +  const navigate = useNavigate();
401 응답에 처리하는 부분은 `instance/index.ts` 파일에 추가하는 방식으로 진행하면 될까요?

2024-10-30 16:56 UTC, HyeonChae1104 commented on src/api/hooks/useHandleKakaoLogin.ts
> +export const useHandleKakaoLogin = () => {
저도 하다 보니 다른 부분에서는 필요가 없을 것 같아 파일을 삭제하였습니다.!

2024-10-31 02:20 UTC, geongyu09 reviewed
고생이 많으시네요
코드 관련해서 커맨트 남겼습니다
시간이 얼마 남지 않은 시점에서 돌아가는 코드를 수정해달라는건 조금 부담이 될 수밖에 없으니, 답변을 듣고 approve하도록 하겠습니다

2024-10-31 02:20 UTC, geongyu09 commented on src/pages/Login/FailurePage.tsx
> +    window.location.href = `${baseURL}/login`
혹시 해당 로직이 어떤 기능을 하는지 설명해주실 수 있나요..?
문장만 보면 api 요청에 사용되는 기초 url에 /login으로 리다이렉트 시키는 로직같은데, 
제가 이해가 잘 안되는 부분이 있는 것 같아요

2024-10-31 02:20 UTC, geongyu09 commented on src/pages/Login/SuccessPage.tsx
> +        localStorage.setItem("accessToken", newAccessToken);
토큰은 로컬에 저장하는 방식으로 결정하신건가요??
그렇다면 이전에 만들어두었던 storage를 사용하는게 맞을 것 같아요
아마 로컬스토리지코드는 작성 안되어있을텐데 작성 후에 사용하는게 좋아보이네요

2024-10-31 02:20 UTC, geongyu09 commented on src/pages/Login/SuccessPage.tsx
> +    reissueAccessToken().then(() => {
이 부분도 잘 이해를 못하였는데요.. 
성공 페이지에서 토큰 발급이 아니라 재발급을 하는거면, 이전에 토큰을 발급하는 절차가 또 있나요?

2024-10-31 02:20 UTC, geongyu09 commented on src/pages/Login/SuccessPage.tsx
> +    try {
axios문이 컴포넌트에 있고, 이전에 만들어둔 인스턴스를 사용하지 않고있고, 요청 api 문을 useEffect를 사용하여 수행하는 과정으로 작성하셨는데,
기존에 작업을 해왔던 계층구조와 추상화 레벨을 어기게 된다면, 그에대한 합당한 이유가 있어야 한다고 생각해요

다른 팀원들을 설득할만한 부분이 혹시 있나요? 작성하신 이유가 궁금합니다!

2024-10-31 02:23 UTC, geongyu09 commented on src/api/hooks/useFetchWithToken.ts
> +  const navigate = useNavigate();
넵 적절히 추가해주시면 좋을 것 같아요

2024-10-31 03:31 UTC, Da-Yeon-Kim reviewed
저도 토큰 쪽이 이해가 잘 안 가는데 한 번만 동작이 흘러가는 과정을 설명해주실 수 있을까요? 그리고 `onboardingPage`와 `LoginPage`의 기능이 무엇이 다른지도 잘 모르겠어요😥 왜 `LoginPage`가 따로 있는 건가요?!

2024-10-31 03:31 UTC, Da-Yeon-Kim commented on src/pages/Login/SuccessPage.tsx
> +    try {
이게 무슨 말씀이시냐면, 저희는 지금 `@/api/hooks` 폴더에 백과 API 소통을 하는 코드들을 따로 분리해 관리하고 있어요.  `@/api/instance` 파일에 이미 만들어둔 axois문과 instance가 있고, 다른 훅들은 이를 활용한 `fetchWithToken`을 사용합니다. 그리고 스케줄링은 `useQuery`를 통해서 하고 있고요!

그런데 지금 이 SuccessPage에서는 기존에 만들어둔 걸 활용 안 하고, 직접 axois문부터 구현하고 계셔서 여쭤보는 겁니다! (그리고 분리도 되어있지 않고요!)

2024-10-31 03:31 UTC, Da-Yeon-Kim commented on src/pages/Login/SuccessPage.tsx
> +        localStorage.setItem("accessToken", newAccessToken);
참고로 storage 코드는 `@/utils/storage`에 있습니다. 😊

2024-10-31 04:46 UTC, HyeonChae1104 commented on src/pages/Login/SuccessPage.tsx
> +    reissueAccessToken().then(() => {
백에서 로그인이 성공하면 쿠키에 refresh token만 담아 해당 페이지로 redirect 시킵니다. 
그럼 프론트는 `reissueAccessToken` 함수를 호출하여 쿠키를 포함한 요청을 다시 백으로 보내서 accessToken을 발급 받는 과정입니다!

따라서 재발급이라고 표현하였습니다!

2024-10-31 04:54 UTC, HyeonChae1104 commented on src/pages/Login/SuccessPage.tsx
> +    try {
오.. 맞네요.. 자세하게 설명도 해주셔서 감사합니당..ㅜ
두 분 말씀대로 코드를 수정하는게 좋을 것 같습니다.!

이 부분부터 수정해보겠습니다!

2024-10-31 04:56 UTC, HyeonChae1104 commented on src/pages/Onboarding/index.tsx
> +  handleKakaoLogin: () => void; // props로 로그인 로직을 받음
해당 부분도 반영하였습니다.! 꼼꼼하게 봐주셔서 감사합니다!

2024-10-31 05:00 UTC, HyeonChae1104 commented on src/pages/Login/SuccessPage.tsx
> +        localStorage.setItem("accessToken", newAccessToken);
원래대로 토큰은 로컬에 저장하는 방식을 사용하기로 하였습니다! 기존의 `@/utils/storage` 파일에서 localStorage코드를 추가하도록 하겠습니다.!

감사합니다!

2024-10-31 05:27 UTC, HyeonChae1104 commented on src/pages/Login/FailurePage.tsx
> +    window.location.href = `${baseURL}/login`
백에서 `@GetMapping("/login")` 코드를 쓰셔서 저도 `window.location.href = `${baseURL}/login` `으로 구현을 하였습니다!

+ /login으로 엔드포인트를 사용하신걸로 판단했습니다!

2024-10-31 05:38 UTC, HyeonChae1104 commented on src/pages/Login/FailurePage.tsx
> +    window.location.href = `${baseURL}/login`
하지만 제 생각으로는 FailurePage는 거의 사용되지 않을 것으로 예상됩니다.

카카오로그인 서버나 잘못된 인증코드 등의 문제가 생길경우 자체적으로 처리를 한다고 알고 있고, 
토큰 만료나 유효하지 않은 경우 401 응답이 나오게 되고, 그 부분은 `instance/index` 파일에 추가할 것이기 때문에 이 페이지는 사용되지 않을 것 같습니다. 

하지만 백에서 요청해주신 부분이라 Login/index.tsx 에서 사용한 로직을 그대로 옮겨와서 구현했습니다!

2024-10-31 07:10 UTC, geongyu09 commented on src/pages/Login/SuccessPage.tsx
> +    reissueAccessToken().then(() => {
설명 감사합니다! 이 상황이라면 재요청이라고 하는게 맞는 표현 같네요

2024-10-31 07:13 UTC, geongyu09 approved these changes
제 의문점은 다 해결되어서 일단 approve하겠습니다! 
이후에 코드상의 문제는 연결하면서 수정하면 되지 않을까 싶습니다

2024-10-31 08:07 UTC, Da-Yeon-Kim approved these changes
저도 일단은 approve 해두겠습니다!
헷갈리는 저를 위해사 `onboardingPage` 외에 `LoginPage`가
따로 있는 이유만 살짝 설명 부탁 드려요😥

2024-10-31 12:47 UTC, HyeonChae1104 commented
어이고..! 제가 생각을 해보느라 답변이 늦어졌네요.! 죄송합니다
다연님이 로그인 페이지가 존재하는 이유에 대해 궁금해하신 점이 저도 이해가 됩니당,,

저도 질문을 받고 고민을 해봤는데, 로그인페이지가 사용되는 일은 2가지였습니다.! 온보딩 페이지에서 로그인 버튼을 통해 로그인 페이지로 넘어가는 것, 401 응답을 받아 SuceessPage에서 refresh-token을 재발급 받는 것을 시도하고 실패하면 로그인 페이지로 넘어가도록 생각을 했었습니다.

하지만 두 과정 모두 불필요한 작업이라고 생각이 드네요.!! 
온보딩 화면에서 로그인 버튼을 통해 바로 백엔드 로그인 로직으로 넘어가도록 수정하고, 401 응답을 받은 상황에서 토큰 재발급에 실패할 경우에도 백엔드 로그인 로직으로 바로 넘어가는 걸로 수정하는게 좋을 것 같습니다!

꼼꼼하게 살펴봐주셔서 감사합니다!!

2024-10-31 18:18 UTC, HyeonChae1104 commented
어제 리뷰 주신 내용을 전부 반영해보았습니다.
머지 전에 확인 부탁드립니다!

2024-11-01 03:32 UTC, geongyu09 approved these changes
확인했습니다
이후의 수정은 백엔드와 헙업하면서 고쳐나가도 충분해 보입니다

2024-11-01 03:32 UTC, geongyu09 commented on src/pages/Login/FailurePage.tsx
> +    window.location.href = `${baseURL}/login`
아무튼 api 요청을 하는것이 아니라 리다이랙트를 하는것이 맞는 것이죠..?

추가적으로 baseURL은 이미 만들어져있습니다. 해당 값을 사용해도 좋아보이네요

2024-11-01 03:32 UTC, geongyu09 commented on src/pages/Login/SuccessPage.tsx
> +      console.error('토큰을 가져오던 중 에러 발생', error);
이전보다 훨씬 좋은 코드가 되었네요

추가적으로 고민(만)해볼 부분 몇가지 남겨보면,
1. 성공 페이지에서 토큰 발급시에 에러가 발생하게 되면 콘솔만 찍고 끝나게 되어야 할까요? 아니면 유저 입장에서 토큰 발급에서 에러가 발생하면 어떤 화면을 보게 될까요? 
2. 재발급 요청은 언제 해야할까요? 단순히 로그인할때 토큰을 얻고자 하는것은 아닐거에요. 추후에 토큰이 만료 되었을 때 refrechToken이 있다면 다시 accessToken을 받을때 주로 사용할텐데, 이걸 어느계층에서 하는게 좋을까요?

2024-11-01 05:34 UTC, merged